### ISSUE TITLE
Modern SSH hostkey methods compatibility

### ISSUE THREAD

**Issue by Grundik** [php/pecl-networking-ssh2#63]
According to documentation, ssh2_connect currently supports only ssh-rsa and ssh-dss hostkey methods, but both of them are deprecated:
* ssh-dss disabled since OpenSSH 7.0 (2015)
* ssh-rsa disabled since OpenSSH 8.8 (2021)

So, its unable to connect to server, which uses modern OpenSSH versions.

Library should be updated to support more modern hostkey methods.

**Comment by langemeijer** [comment]
Did you verify that ssh2_connect() is not working with servers without dss or rsa?

glancing over the [ssh2_](https://github.com/php/pecl-networking-ssh2/blob/master/ssh2.c#L299) does not reveal anything specific to either ssh-rsa or ssh-dss. 

At the time the documentation was written, both hostkey methods probably were the only two. As the ssh2 extension is only a thin wrapper over libssh2, the supported hostkey methods probably are defined by what your libssh2 capabilities. ed25519 and ECDH is support has been in libssh2 since 2018-ish, so any recent version could very well work.

Could you check? In that case this is a documentation issue.

**Comment by rfay** [comment]
I'd be interested to know whether you tracked this to a particular libssh2 problem? I'd also be interested in why it was "closed as completed".
